spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis01?useSSL=false
    username: root
    password: student
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
